xpos334/xpos334/Controllers/CategoryTryController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.Services;
using xpos334.viewmodels;

namespace xpos334.Controllers
{
    public class CategoryTryController : Controller
    {
        private readonly XPOS_334Context db;
        private readonly CategoryTryService categoryTryService;
        public CategoryTryController(XPOS_334Context _db)
        {
            db = _db;
            this.categoryTryService = new CategoryTryService(db);
        }
        public IActionResult Index()
        {
            List<VMTblCategory> dataView = categoryTryService.GetAllData();
            
            return View(dataView);
        }

        public IActionResult Create()
        {
            VMTblCategory dataView = new VMTblCategory();
            return PartialView(dataView);
            //return View(dataView); //pakai layout null
        }

        [HttpPost]
        public IActionResult Create(VMTblCategory dataView)
        {
            VMResponse response = new VMResponse();
            //TblCategory data = new TblCategory();
            //data.NameCategory = dataView.NameCategory;
            //db.TblCategories.Add(data);

            if(ModelState.IsValid)
            {
                response = categoryTryService.Create(dataView);

                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            response.Entity = dataView;
            return View(response.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return PartialView(dataView);
        }

        [HttpPost]
        public IActionResult Edit(VMTblCategory dataView)
        {
            VMResponse response = new VMResponse();

            if(ModelState.IsValid)
            {
                response = categoryTryService.Edit(dataView);

                if(response.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            response.Entity = dataView;
            return View(response.Entity);
        }
        public IActionResult Detail(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return PartialView(dataView);
        }

        public IActionResult Delete(int id)
        {
			VMTblCategory dataView = categoryTryService.GetById(id);
            Console.WriteLine("Ini"+dataView);
			return PartialView(dataView);
		}

        [HttpPost]
		public IActionResult Delete(VMTblCategory dataView)
		{
            VMResponse response = categoryTryService.Delete(dataView);

			if (response.Success)
			{
				return RedirectToAction("Index");
			}

			return View(response.Entity);
		}
	}
}

xpos334/xpos334/Views/CategoryTry/Create.cshtml
@using xpos334.viewmodels
@model VMTblCategory

@{
	//Layout = null;
	ViewData["Title"] = "Create Category Try";
}

<div class="card">
	<div class="card-body">
		<div class="h4 mb-4">@ViewData["Title"]</div>

		<form asp-action="Create" method="post">
			<div class="row mb-4">
				<label for="NameCategory" class="col-sm-4 col-form-label">Category Name</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
					<span asp-validation-for="NameCategory" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-4">
				<label for="Description" class="col-sm-4 col-form-label">Description</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-4">
				<div class="col-sm-10">
					<button type="submit" class="btn btn-primary">Submit</button>
					<a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Back to List</a>
				</div>
			</div>
		</form>

	</div>
</div>

xpos334/xpos334/Views/CategoryTry/Delete.cshtml
@using xpos334.viewmodels
@model VMTblCategory

@{
	ViewData["Title"] = "Delete Category Try";
}

<div class="card">
	<div class="card-body">
		<div class="h4 mb-4">@ViewData["Title"]</div>

		<form asp-action="Delete" method="post">
			<input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">

			<div class="row mb-4">
				<div class="col-sm-10">
					<button class="btn btn-danger" type="submit">Delete</button>
					<a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Cancel</a>
				</div>
			</div>
		</form>
	</div>
</div>

xpos334/xpos334/Views/CategoryTry/Detail.cshtml
@using xpos334.viewmodels
@model VMTblCategory

@{
	ViewData["Title"] = "Detail Category Try";
}

<div class="card">
	<div class="card-body">
		<div class="h4 mb-4">@ViewData["Title"]</div>

		<div class="row mb-4">
			<label for="NameCategory" class="col-sm-4 col-form-label">Category Name</label>
			<div class="col-sm-8">
				<input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
			</div>
		</div>

		<div class="row mb-4">
			<label for="Description" class="col-sm-4 col-form-label">Description</label>
			<div class="col-sm-8">
				<input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
			</div>
		</div>

		<div class="row mb-4">
			<div class="col-sm-10">
				<a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Back to List</a>
			</div>
		</div>

	</div>
</div>

xpos334/xpos334/Views/CategoryTry/Edit.cshtml
@using xpos334.viewmodels
@model VMTblCategory

@{
	ViewData["Title"] = "Edit Category Try";
}

<div class="card">
	<div class="card-body">
		<div class="h4 mb-4">@ViewData["Title"]</div>

		<form asp-action="Edit" method="post">
			<input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id" >

			<div class="row mb-4">
				<label for="NameCategory" class="col-sm-4 col-form-label">Category Name</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
					<span asp-validation-for="NameCategory" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-4">
				<label for="Description" class="col-sm-4 col-form-label">Description</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-4">
				<div class="col-sm-10">
					<button type="submit" class="btn btn-primary">Submit</button>
					<a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Back to List</a>
				</div>
			</div>
		</form>

	</div>
</div>

xpos334/xpos334/Views/CategoryTry/Index.cshtml
@using xpos334.viewmodels;

@{
	ViewData["Title"] = "Category Try";
}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">@ViewData["Title"]</h5>

        <button type="button" class="btn btn-primary" id="btn_create">Create</button>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Name Category</th>
                    <th scope="col">Description</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>

            <tbody>
                @{int count = 0;
                    foreach(VMTblCategory item in Model)
                    {
                        ++count;
                        <tr>
                            <td scope="row">@count</td>
                            <td>@item.NameCategory</td>
                            <td>@item.Description</td>
                            <td>
                                <a class="btn btn-primary btn_edit" data-id="@item.Id">Edit</a>
                                <a class="btn btn-success btn_detail" data-id="@item.Id">Detail</a>
                                <a class="btn btn-danger btn_delete" data-id="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    $("#btn_create").click(function() {
        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Create")
        $("#my_modal").modal("show")
    })

    $(".btn_edit").click(function(){
        var id = $(this).data("id") //panggil data-id
        
        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Edit?id=" + id)
        $("#my_modal").modal("show")
    })

    $(".btn_detail").click(function () {
        var id = $(this).data("id") //panggil data-id

        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Detail?id=" + id)
        $("#my_modal").modal("show")
    })

    $(".btn_delete").click(function () {
        var id = $(this).data("id") //panggil data-id

        $("#modal_body").empty()
        $("#modal_body").load("/CategoryTry/Delete?id=" + id)
        $("#my_modal").modal("show")
    })
</script>