xpos334/xpos334/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.Services;
using xpos334.viewmodels;

namespace xpos334.Controllers
{
	public class CategoryController : Controller
	{
		private CategoryService categoryService;
		private int IdUser = 1;

        public CategoryController(CategoryService _categoryService)
        {
            categoryService = _categoryService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.CurrentPageSize = pageSize;
			ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

			if(searchString != null)
			{
				pageNumber = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewBag.CurrentFilter = searchString;

			List<TblCategory> data = await categoryService.GetAllData();

			if(!string.IsNullOrEmpty(searchString))
			{
				data = data.Where(a => a.NameCategory.ToLower().Contains(searchString.ToLower())
				|| a.Description.ToLower().Contains(searchString.ToLower())).ToList();
			}

			switch (sortOrder)
			{
				case "name_desc": 
					data = data.OrderByDescending(a => a.NameCategory).ToList();
					break;
				default:
					data = data.OrderBy(a => a.NameCategory).ToList();
					break;
			}

			return View(PaginatedList<TblCategory>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
		}

		public IActionResult Create()
		{
			TblCategory data = new TblCategory();
			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> Create(TblCategory dataParam)
		{
			dataParam.CreateBy = IdUser;
			VMResponse response = await categoryService.Create(dataParam);

			if (response.Success)
			{
				return Json(new { dataResponse = response });
			}

			return View(dataParam);
		}

		public async Task<JsonResult> CheckNameIsExist(string nameCategory, int id)
		{
			bool isExist = await categoryService.CheckCategoryByName(nameCategory, id);
			return Json(isExist);
		}

		public async Task<IActionResult> Edit(int id)
		{
			TblCategory data = await categoryService.GetDataById(id);
			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(TblCategory dataParam)
		{
			dataParam.UpdateBy = IdUser;
			VMResponse response = await categoryService.Edit(dataParam);

			if(response.Success)
			{
				return Json(new { dataResponse = response });
			}

			return View(dataParam);
		}

		public async Task<IActionResult> Detail(int id)
		{
			TblCategory data = await categoryService.GetDataById(id);
			return PartialView(data);
		}

		public async Task<IActionResult> Delete(int id)
		{
			TblCategory data = await categoryService.GetDataById(id);
			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> SureDelete(int id)
		{
			int createBy = IdUser;
			VMResponse response = await categoryService.Delete(id, createBy);

			if(response.Success)
			{
				return Json(new { dataResponse = response });
				//return RedirectToAction("Index");
            }

			return RedirectToAction("Index");
		}
	}
}

xpos334/xpos334/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.Models;

namespace xpos334.Controllers
{
	public class FriendController : Controller
	{
		private static List<Friend> friends = new List<Friend>()
		{
			new Friend(){Id = 1, Name = "Irvan", Address = "Kemayoran"},
			new Friend(){Id = 2, Name = "Tunggul", Address = "Cilandak"},
			new Friend(){Id = 3, Name = "Shabrina", Address = "Radio Dalam"}
		};

		public IActionResult Index()
		{
			ViewBag.listFriends = friends;
			//return View(friends);
			return View();
		}

		public IActionResult Create()
		{

			return View();
		}

		[HttpPost]
        public IActionResult Create(Friend friend)
        {
			friends.Add(friend);
            return RedirectToAction("Index");
        }

		public IActionResult Edit(int id)
		{
			//Friend friend = friends[id];
			Friend friend = friends.Find(a => a.Id == id);
			return View(friend);
		}

		[HttpPost]
		public IActionResult Edit(Friend data)
		{
            Friend friend = friends.Find(a => a.Id == data.Id);
			int index = friends.IndexOf(friend);

			if(index > -1)
			{
				friends[index].Name = data.Name;
				friends[index].Address = data.Address;
            }

			return RedirectToAction("Index");
        }

		public IActionResult Detail(int id)
		{
			Friend friend = friends.Find(a => a.Id == id);
			return View(friend);
		}

		public IActionResult Delete(int id)
		{
			Friend friend = friends.Find(a => a.Id == id);
			return View(friend);
		}

		[HttpPost]
		public IActionResult Delete(Friend data)
		{
			Friend friend = friends.Find(a => a.Id == data.Id);
			friends.Remove(friend);
			return RedirectToAction("Index");
		}
    }
}

xpos334/xpos334/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.Services;
using xpos334.viewmodels;

namespace xpos334.Controllers
{
    public class ProductController : Controller
    {
        private CategoryService categoryService;
        private VariantService variantService;
        private ProductService productService;
        private int IdUser = 1;

        public ProductController(CategoryService _categoryService, VariantService _variantService, ProductService _productService)
        {
            categoryService = _categoryService;
            variantService = _variantService;
            productService = _productService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSort = sortOrder == "price" ? "price_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblProduct> data = await productService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameProduct.ToLower().Contains(searchString.ToLower())
                || a.NameVariant.ToLower().Contains(searchString.ToLower())
                || a.NameCategory.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameProduct).ToList();
                    break;
                case "price_desc":
                    data = data.OrderByDescending(a => a.Price).ToList();
                    break;
                case "price":
                    data = data.OrderBy(a => a.Price).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameProduct).ToList();
                    break;
            }
            return View(PaginatedList<VMTblProduct>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<IActionResult> Create()
        {
            VMTblProduct data = new VMTblProduct();

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;  
            
            List<VMTblVariant> listVariant = await variantService.GetAllData();
            ViewBag.ListVariant = listVariant;

            return PartialView(data);
        }
    }
}

xpos334/xpos334/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Framework;
using System.Drawing.Printing;
using xpos334.datamodels;
using xpos334.Services;
using xpos334.viewmodels;

namespace xpos334.Controllers
{
    public class VariantController : Controller
    {
        private CategoryService categoryService;
        private VariantService variantService;
        private int IdUser = 1;

        public VariantController(CategoryService _categoryService, VariantService _variantService)
        {
            categoryService = _categoryService;
            variantService = _variantService;
        }
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblVariant> data = await variantService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameCategory.ToLower().Contains(searchString.ToLower()) 
                || a.NameVariant.ToLower().Contains(searchString.ToLower())
                || a.Description.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameCategory).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameCategory).ToList();
                    break;
            }

        return View(PaginatedList<VMTblVariant>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }
		public async Task<JsonResult> CheckNameIsExist(string nameVariant, int id, int idCategory)
		{
			bool isExist = await variantService.CheckByName(nameVariant, id, idCategory);
			return Json(isExist);
		}
        
        public async Task<IActionResult> Create()
        {
            VMTblVariant data = new VMTblVariant();

            //Get all data master category
            List<TblCategory> listCategories = await categoryService.GetAllData();
            ViewBag.ListCategories = listCategories;
            //Console.WriteLine("testttt");
            return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> Create(VMTblVariant dataParam)
		{
			dataParam.CreateBy = IdUser;
			VMResponse response = await variantService.Create(dataParam);

			if (response.Success)
			{
				return Json(new { dataResponse = response });
			}

			return View(dataParam);
		}

		public async Task<IActionResult> Edit(int id)
		{
			VMTblVariant data = await variantService.GetDataById(id);

			//Get all data master category
			List<TblCategory> listCategories = await categoryService.GetAllData();
			ViewBag.ListCategories = listCategories;

			return PartialView(data);
		}

        [HttpPost]
		public async Task<IActionResult> Edit(VMTblVariant dataParam)
		{
			VMResponse response = await variantService.Edit(dataParam);

			if (response.Success)
			{
				return Json(new { dataResponse = response });
			}

			return View(dataParam);
		}

        public async Task<IActionResult> Detail(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);

            return PartialView(data);
        }

		public async Task<IActionResult> Delete(int id)
		{
			VMTblVariant data = await variantService.GetDataById(id);

			return PartialView(data);
		}

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse response = await variantService.Delete(id);

            if (response.Success)
            {
                return Json(new {dataResponse  = response});
            }

            return RedirectToAction("Index");
        }
	}
}

xpos334/xpos334/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../assets/images/favicon.png">
    <title>Adminmart Template - The Ultimate Multipurpose admin template</title>
    <script src="~/AdminMart/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <!-- Custom CSS -->
    <link href="~/AdminMart/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="~/AdminMart/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="~/AdminMart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/AdminMart/dist/css/style.min.css" rel="stylesheet">
    <!-- Toastr -->
    <script src="~/AdminMart/plugins/plugins/toastr/toastr.min.js"></script>
    <link rel="stylesheet" href="~/AdminMart/plugins/plugins/toastr/toastr.min.css" />
    <!-- Sweetalert2 -->
    <script src="~/AdminMart/plugins/plugins/sweetalert2/sweetalert2.js"></script>
</head>
<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>

    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full" data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">

        <partial name="_Header" />

        <partial name="_Sidebar" />

        <div class="page-wrapper">
            <div class="container-fluid">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <footer class="footer text-center text-muted">
                All Rights Reserved by Adminmart. Designed and Developed by <a href="https://wrappixel.com">WrapPixel</a>.
            </footer>
        </div>
     </div>


    <!-- Modal -->
    <div class="modal fade" id="my_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal_body">
                    ...
                </div>
            </div>
        </div>
    </div>

    <script src="~/AdminMart/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/AdminMart/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- apps -->
    <!-- apps -->
    <script src="~/AdminMart/dist/js/app-style-switcher.js"></script>
    <script src="~/AdminMart/dist/js/feather.min.js"></script>
    <script src="~/AdminMart/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/AdminMart/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/AdminMart/dist/js/custom.min.js"></script>
    <!--This page JavaScript -->
    <script src="~/AdminMart/assets/extra-libs/c3/d3.min.js"></script>
    <script src="~/AdminMart/assets/extra-libs/c3/c3.min.js"></script>
    <script src="~/AdminMart/assets/libs/chartist/dist/chartist.min.js"></script>
    <script src="~/AdminMart/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
    <script src="~/AdminMart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js"></script>
    <script src="~/AdminMart/assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/AdminMart/dist/js/pages/dashboards/dashboard1.min.js"></script>
</body>
</html>

xpos334/xpos334/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - xpos334</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/xpos334.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">xpos334</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Friend</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoryTry" asp-action="Index">Category Try</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - xpos334 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Modal -->
    <div class="modal fade" id="my_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal_body">
                    ...
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

xpos334/xpos334/Views/Shared/_Sidebar.cshtml
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" href="index.html"
                       aria-expanded="false">
                        <i data-feather="home" class="feather-icon"></i><span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Master</span></li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Friend" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">
                            Friend
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="CategoryTry" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Category Try</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="VariantTry" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Variant Try</span>
                    </a>
                </li>

                
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Category" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Category</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Variant" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Variant</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Product" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Products</span>
                    </a>
                </li>

                <li class="list-divider"></li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" href="authentication-login1.html"
                       aria-expanded="false">
                        <i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>